
-- brands definition

-- Drop table

-- DROP TABLE brands;

CREATE TABLE IF NOT EXISTS brands (
	brand_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	brand_name varchar(255) NOT NULL,
	CONSTRAINT brands_pkey PRIMARY KEY (brand_id)
);


-- categories definition

-- Drop table

-- DROP TABLE categories;

CREATE TABLE IF NOT EXISTS categories (
	category_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	category_name varchar(255) NOT NULL,
	CONSTRAINT categories_pkey PRIMARY KEY (category_id)
);


-- customers definition

-- Drop table

-- DROP TABLE customers;

CREATE TABLE IF NOT EXISTS customers (
	customer_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	city varchar(50) NULL,
	email varchar(255) NOT NULL,
	first_name varchar(255) NOT NULL,
	last_name varchar(255) NOT NULL,
	phone varchar(25) NULL,
	state varchar(25) NULL,
	street varchar(255) NULL,
	zip_code varchar(5) NULL,
	CONSTRAINT customers_pkey PRIMARY KEY (customer_id)
);


-- stores definition

-- Drop table

-- DROP TABLE stores;

CREATE TABLE IF NOT EXISTS stores (
	store_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	city varchar(255) NULL,
	email varchar(255) NULL,
	phone varchar(25) NULL,
	state varchar(10) NULL,
	store_name varchar(255) NOT NULL,
	street varchar(255) NULL,
	zip_code varchar(5) NULL,
	CONSTRAINT stores_pkey PRIMARY KEY (store_id)
);


-- products definition

-- Drop table

-- DROP TABLE products;

CREATE TABLE IF NOT EXISTS products (
	product_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	list_price numeric(10, 2) NOT NULL,
	model_year int4 NOT NULL,
	product_name varchar(255) NOT NULL,
	brand_id int4 NOT NULL,
	category_id int4 NOT NULL,
	CONSTRAINT products_pkey PRIMARY KEY (product_id),
	CONSTRAINT fka3a4mpsfdf4d2y6r8ra3sc8mv FOREIGN KEY (brand_id) REFERENCES brands(brand_id),
	CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES categories(category_id)
);


-- staffs definition

-- Drop table

-- DROP TABLE staffs;

CREATE TABLE IF NOT EXISTS staffs (
	staff_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	active bool NOT NULL,
	email varchar(255) NOT NULL,
	first_name varchar(50) NOT NULL,
	last_name varchar(50) NOT NULL,
	phone varchar(25) NULL,
	manager_id int4 NULL,
	store_id int4 NOT NULL,
	CONSTRAINT staffs_pkey PRIMARY KEY (staff_id),
	CONSTRAINT uk_ikcos5mg2rbdhyg1v5dbyu5is UNIQUE (email),
	CONSTRAINT fkefpdoo7xl4dp551s13w76pclk FOREIGN KEY (manager_id) REFERENCES staffs(staff_id),
	CONSTRAINT fkm8wik547o9kv83ubgmdct6tm4 FOREIGN KEY (store_id) REFERENCES stores(store_id)
);


-- stocks definition

-- Drop table

-- DROP TABLE stocks;

CREATE TABLE IF NOT EXISTS stocks (
	quantity int4 NULL,
	store_id int4 NOT NULL,
	product_id int4 NOT NULL,
	CONSTRAINT stocks_pkey PRIMARY KEY (product_id, store_id),
	CONSTRAINT fk3refpt5bgpl6xevhc4ey0ct3v FOREIGN KEY (store_id) REFERENCES stores(store_id),
	CONSTRAINT fkff7be959jyco0iukc1dcjj9qm FOREIGN KEY (product_id) REFERENCES products(product_id)
);


-- orders definition

-- Drop table

-- DROP TABLE orders;

CREATE TABLE IF NOT EXISTS orders (
	order_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	order_date date NOT NULL,
	order_status int4 NOT NULL,
	required_date date NOT NULL,
	shipped_date date NULL,
	customer_id int4 NULL,
	staff_id int4 NOT NULL,
	store_id int4 NOT NULL,
	CONSTRAINT orders_pkey PRIMARY KEY (order_id),
	CONSTRAINT fk7vt11rektq6d400j5r1ajw8st FOREIGN KEY (staff_id) REFERENCES staffs(staff_id),
	CONSTRAINT fknqkwhwveegs6ne9ra90y1gq0e FOREIGN KEY (store_id) REFERENCES stores(store_id),
	CONSTRAINT fkpxtb8awmi0dk6smoh2vp1litg FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);


-- order_items definition

-- Drop table

-- DROP TABLE order_items;

CREATE TABLE IF NOT EXISTS order_items (
	item_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	discount numeric(4, 2) NOT NULL,
	list_price numeric(10, 2) NOT NULL,
	quantity int4 NOT NULL,
	order_id int4 NOT NULL,
	product_id int4 NOT NULL,
	CONSTRAINT order_items_pkey PRIMARY KEY (item_id),
	CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES orders(order_id),
	CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES products(product_id)
);